# Generated by Django 4.2.8 on 2023-12-14 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('specialization_id', models.IntegerField(primary_key=True, serialize=False)),
                ('year_of_study', models.DateField()),
                ('specialization_name', models.TextField()),
                ('specialization_syllabus', models.TextField()),
                ('specialization_reference_books', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses')),
            ],
            options={
                'db_table': 'specializations',
            },
        ),
    ]
