# Generated by Django 4.2.8 on 2023-12-20 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('specializations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.courses'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='specialization_syllabus',
            field=models.TextField(blank=True, null=True),
        ),
    ]
