# Generated by Django 4.2.8 on 2023-12-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specializations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='specialization_reference_books',
            field=models.TextField(blank=True, null=True),
        ),
    ]
