# Generated by Django 4.2.8 on 2023-12-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specializations', '0002_alter_specialization_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='specialization_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='specialization_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='year_of_study',
            field=models.DateField(blank=True, null=True),
        ),
    ]
