# Generated by Django 4.2.8 on 2023-12-19 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('questions', '0001_initial'),
        ('parakh_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestQestions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('time_required', models.BigIntegerField(blank=True, null=True)),
                ('correct', models.BooleanField(blank=True, null=True)),
                ('average_time', models.FloatField(blank=True, null=True)),
                ('test_difficulty', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('option_marked', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parakh_test_marked_answer', to='questions.options')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parakh_test_question_attempted', to='questions.questions')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iduser', to='student.student')),
                ('test_attempted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test2user', to='parakh_test.parakh_test')),
            ],
        ),
    ]
