# Generated by Django 4.2.8 on 2023-12-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LevelOfEducation',
            fields=[
                ('level_of_education_id', models.IntegerField(primary_key=True, serialize=False)),
                ('level_of_education_name', models.TextField()),
            ],
            options={
                'db_table': 'level_of_education',
            },
        ),
    ]
