# Generated by Django 4.2.8 on 2023-12-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level_of_education', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelofeducation',
            name='level_of_education_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
