# Generated by Django 4.2.8 on 2023-12-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnalytics',
            fields=[
                ('question_id', models.TextField(db_index=True, primary_key=True, serialize=False)),
                ('total_attempts', models.BigIntegerField()),
                ('total_correct', models.BigIntegerField()),
                ('difficulty', models.FloatField()),
            ],
            options={
                'db_table': 'question_analytics',
            },
        ),
    ]
