# Generated by Django 4.2.8 on 2023-12-19 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('specializations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_proficiency', models.TextField(blank=True, null=True)),
                ('total_attempts', models.TextField(blank=True, null=True)),
                ('accuracy', models.TextField(blank=True, null=True)),
                ('specialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user2special', to='specializations.specialization')),
                ('student_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userid', to='student.student')),
            ],
        ),
    ]
