# Generated by Django 4.2.8 on 2023-12-19 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('level_of_education', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('courses_id', models.IntegerField(primary_key=True, serialize=False)),
                ('courses_name', models.CharField(max_length=255)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='level_of_education.levelofeducation')),
            ],
            options={
                'db_table': 'courses',
            },
        ),
    ]
