# Generated by Django 4.2.8 on 2023-12-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='courses_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
