# Generated by Django 4.2.8 on 2023-12-18 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('option_id', models.TextField(primary_key=True, serialize=False)),
                ('option_title', models.TextField(blank=True, null=True)),
                ('option_attachment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('question_id', models.TextField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('attachment', models.TextField(blank=True, null=True)),
                ('answer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question2option', to='questions.options')),
                ('options', models.ManyToManyField(blank=True, to='questions.options')),
            ],
        ),
    ]
