# Generated by Django 4.2.8 on 2023-12-20 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specializations', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('option_id', models.TextField(primary_key=True, serialize=False)),
                ('option_title', models.TextField(blank=True, null=True)),
                ('option_attachment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'options',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('attachment', models.TextField(blank=True, null=True)),
                ('answer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question2option', to='questions.options')),
                ('options', models.ManyToManyField(blank=True, to='questions.options')),
                ('specialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ques2special', to='specializations.specialization')),
            ],
            options={
                'db_table': 'questions',
            },
        ),
    ]
