# Generated by Django 4.2.8 on 2023-12-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='difficulty',
            field=models.FloatField(default=0.5),
        ),
    ]
