# Generated by Django 4.2.8 on 2023-12-19 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specializations', '0001_initial'),
        ('questions', '0002_alter_questions_answer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ques2special', to='specializations.specialization'),
        ),
        migrations.AlterModelTable(
            name='options',
            table='options',
        ),
        migrations.AlterModelTable(
            name='questions',
            table='questions',
        ),
    ]
