# Generated by Django 4.2.8 on 2023-12-19 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_questions_specialization_alter_options_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='question_id',
            new_name='id',
        ),
    ]
