# Generated by Django 4.2.8 on 2023-12-19 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('specializations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parakh_Test',
            fields=[
                ('test_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('specialization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specializations.specialization')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'db_table': 'parakh_test',
            },
        ),
    ]
