# Generated by Django 4.2.8 on 2024-01-28 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specializations', '__first__'),
        ('student', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parakh_Test',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('average_time', models.FloatField(blank=True, null=True)),
                ('test_difficulty', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('specialization_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='specializations.specialization')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'db_table': 'parakh_test',
            },
        ),
    ]
