# Generated by Django 4.2.8 on 2023-12-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parakh_test', '0001_initial'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='parakh_test',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parakh_test',
            name='average_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parakh_test',
            name='test_difficulty',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
