# Generated by Django 4.2.8 on 2023-12-20 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specializations', '__first__'),
        ('parakh_test', '0002_remove_parakh_test_date_parakh_test_accuracy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parakh_test',
            name='date',
        ),
        migrations.AlterField(
            model_name='parakh_test',
            name='specialization_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='specializations.specialization'),
        ),
    ]
