# Generated by Django 4.2.8 on 2023-12-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parakh_test', '0003_remove_parakh_test_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parakh_test',
            name='test_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
